version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: asif/travel-booking-portal:1.0
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - EMAIL_SMTP_USERNAME=${EMAIL_SMTP_USERNAME}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    depends_on:
      - mongodb
    networks:
      - go-network

  mongodb:
    image: mvertes/alpine-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - mongodb:/var/lib/mongodb/data
    networks:
      - go-network

volumes:
  mongodb:

networks:
  go-network:
    driver: bridge
