swagger: "2.0"
info:
  description: "Travel Booking Portal API (Microservices)"
  version: "1.0.0"
  title: "Travel Booking Portal"

host: "localhost:8080"
basePath: "/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /user:
    post:
      operationId: "CreateUser"
      parameters:
        - in: "body"
          name: "user"
          description: "User object to create "
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "User added successfully"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Bad Request - The request is invalid or contains errors"
        409:
          description: "User already exists"
        500:
          description: "Internal Server Error"
    put:
      operationId: "UpdateUser"
      parameters:
        - in: "body"
          name: "user"
          description: "User object to update"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "User updated successfully"
          schema:
            $ref: "#/definitions/User"
        200:
          description: "User updated successfully"
          schema:
            $ref: "#/definitions/User"

        400:
          description: "Bad Request - The request is invalid or contains errors"
        404:
          description: "User already exists"
        500:
          description: "Internal Server Error"
    get:
      operationId: "ListUsers"
      responses:
        200:
          description: "List of Users retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        404:
          description: "User not found"
        500:
          description: "Internal Server Error"
  /user/{userID}:
    get:
      operationId: "GetUser"
      parameters:
        - name: userID
          in: path
          required: true
          type: "integer"
          description: "ID of the user to retrieve"
      responses:
        200:
          description: "User retrieved successfully"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
        500:
          description: "Internal Server Error"
    delete:
      operationId: "DeleteUser"
      parameters:
        - name: "userID"
          in: "path"
          description: "ID of the USer to delete"
          required: true
          type: "integer"
      responses:
        204:
          description: "User deleted successfully"
        404:
          description: "USer not found"
        500:
          description: "Internal Server Error"

  /booking:
    post:
      operationId: "CreateBooking"
      parameters:
        - in: "body"
          name: "booking"
          description: "Booking object to create "
          required: true
          schema:
            $ref: "#/definitions/Booking"
      responses:
        201:
          description: "Booking added successfully"
          schema:
            $ref: "#/definitions/Booking"

        400:
          description: "Bad Request - The request is invalid or contains errors"
        409:
          description: "Booking already exists"

        409:
          description: "Booking already exists"
        500:
          description: "Internal Server Error"
    put:
      operationId: "UpdateBooking"
      parameters:
        - in: "body"
          name: "booking"
          description: "Booking object to update"
          required: true
          schema:
            $ref: "#/definitions/Booking"
      responses:
        200:
          description: " updated successfully"
          schema:
            $ref: "#/definitions/Booking"
        201:
          description: "Booking updated successfully"
          schema:
            $ref: "#/definitions/Booking"
        400:
          description: "Bad Request - The request is invalid or contains errors"
        409:
          description: "Booking already exists"

        404:
          description: "Booking not found"
        500:
          description: "Internal Server Error"
    get:
      operationId: "ListBookings"
      responses:
        200:
          description: "List of bookings retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Booking"
        404:
          description: "Booking not found"

        500:
          description: "Internal Server Error"
  /booking/{bookingID}:
    get:
      operationId: "GetBooking"
      parameters:
        - name: "bookingID"
          in: "path"
          description: "ID of the booking to retrieve"
          required: true
          type: "integer"
      responses:
        200:
          description: "Booking retrieved successfully"
          schema:
            $ref: "#/definitions/Booking"
        404:
          description: "Booking not found"
        500:
          description: "Internal Server Error"
    delete:
      operationId: "DeleteBooking"
      parameters:
        - name: "bookingID"
          in: "path"
          description: "ID of the booking to delete"
          required: true
          type: "integer"
      responses:
        400:
          description: "Bad Request - The request is invalid or contains errors"
        204:
          description: "Booking deleted successfully"
        404:
          description: "Booking not found"
        500:
          description: "Internal Server Error"

  /car:
    post:
      operationId: "CreateCar"
      parameters:
        - in: "body"
          name: "car"
          description: "CarRental object to create"
          required: true
          schema:
            $ref: "#/definitions/CarRental"
      responses:
        201:
          description: "CarRental added successfully"
          schema:
            $ref: "#/definitions/CarRental"
        409:
          description: "CarRental already exists"
        400:
          description: "Bad Request - The request is invalid or contains errors"
        500:
          description: "Internal Server Error"
    put:
      operationId: "UpdateCar"
      parameters:
        - in: "body"
          name: "car"
          description: "CarRental object toupdate"
          required: true
          schema:
            $ref: "#/definitions/CarRental"
      responses:
        200:
          description: " updated successfully"
          schema:
            $ref: "#/definitions/CarRental"
        201:
          description: "CarRental updated successfully"
          schema:
            $ref: "#/definitions/CarRental"
        404:
          description: "CarRental not found"
        400:
          description: "Bad Request - The request is invalid or contains errors"
        500:
          description: "Internal Server Error"
    get:
      operationId: "ListCars"
      responses:
        200:
          description: "List of Cars retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/CarRental"
        404:
          description: "Cars not found"
        500:
          description: "Internal Server Error"
  /car/{carID}:
    get:
      operationId: "GetCar"
      parameters:
        - name: "carID"
          in: "path"
          description: "ID of the Car to retrieve"
          required: true
          type: "integer"
      responses:
        200:
          description: "Car retrieved successfully"
          schema:
            $ref: "#/definitions/CarRental"
        404:
          description: "Car not found"
        500:
          description: "Internal Server Error"
    delete:
      operationId: "DeleteCar"
      parameters:
        - name: "carID"
          in: "path"
          description: "ID of the Car to delete"
          required: true
          type: "integer"
      responses:
        204:
          description: "Car deleted successfully"
        404:
          description: "Car not found"
        500:
          description: "Internal Server Error"

  /hotel:
    post:
      operationId: "CreateHotel"
      parameters:
        - in: "body"
          name: "hotel"
          description: "Hotel object to create"
          required: true
          schema:
            $ref: "#/definitions/Hotel"
      responses:
        201:
          description: "Hotel added successfully"
          schema:
            $ref: "#/definitions/Hotel"
        400:
          description: "Bad Request - The request is invalid or contains errors"
        409:
          description: "Hotel already exists"
        500:
          description: "Internal Server Error"
    put:
      operationId: "UpdateHotel"
      parameters:
        - in: "body"
          name: "hotel"
          description: "Hotel object to  update"
          required: true
          schema:
            $ref: "#/definitions/Hotel"
      responses:
        200:
          description: " updated successfully"
          schema:
            $ref: "#/definitions/Hotel"
        201:
          description: "Hotel updated successfully"
          schema:
            $ref: "#/definitions/Hotel"
        400:
          description: "Bad Request - The request is invalid or contains errors"
        404:
          description: "Hotel not found"
        500:
          description: "Internal Server Error"
    get:
      operationId: "ListHotels"
      responses:
        200:
          description: "List of Hotels retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Hotel"
        404:
          description: "Hotels not found"
        500:
          description: "Internal Server Error"
  /hotel/{hotelID}:
    get:
      operationId: "GetHotel"
      parameters:
        - name: "hotelID"
          in: "path"
          description: "ID of the Hotel to retrieve"
          required: true
          type: "integer"
      responses:
        200:
          description: "Hotel retrieved successfully"
          schema:
            $ref: "#/definitions/Hotel"
        404:
          description: "Hotel not found"
        500:
          description: "Internal Server Error"
    delete:
      operationId: "DeleteHotel"
      parameters:
        - name: "hotelID"
          in: "path"
          description: "ID of the Hotel to delete"
          required: true
          type: "integer"
      responses:
        204:
          description: "Hotel deleted successfully"
        404:
          description: "Hotel not found"
        500:
          description: "Internal Server Error"
  /room:
    post:
      operationId: "CreateRoom"
      parameters:
        - in: "body"
          name: "room"
          description: "Room object to create"
          required: true
          schema:
            $ref: "#/definitions/Room"
      responses:
        201:
          description: "Room added successfully"
          schema:
            $ref: "#/definitions/Room"
        400:
          description: "Bad Request - The request is invalid or contains errors"
        409:
          description: "Room already exists"
        500:
          description: "Internal Server Error"
    put:
      operationId: "UpdateRoom"
      parameters:
        - in: "body"
          name: "room"
          description: "Room object to  update"
          required: true
          schema:
            $ref: "#/definitions/Room"
      responses:
        200:
          description: "Room updated successfully"
          schema:
            $ref: "#/definitions/Room"
        201:
          description: "Room updated successfully"
          schema:
            $ref: "#/definitions/Room"
        400:
          description: "Bad Request - The request is invalid or contains errors"
        404:
          description: "Room not found"
        500:
          description: "Internal Server Error"
    get:
      operationId: "ListRooms"
      responses:
        200:
          description: "List of Rooms retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Room"
        404:
          description: "Rooms not found"
        500:
          description: "Internal Server Error"
  /room/{roomID}:
    get:
      operationId: "GetRoom"
      parameters:
        - name: "roomID"
          in: "path"
          description: "ID of the Room to retrieve"
          required: true
          type: "integer"
      responses:
        200:
          description: "Room retrieved successfully"
          schema:
            $ref: "#/definitions/Room"
        404:
          description: "Room not found"
        500:
          description: "Internal Server Error"
    delete:
      operationId: "DeleteRoom"
      parameters:
        - name: "roomID"
          in: "path"
          description: "ID of the Room to delete"
          required: true
          type: "integer"
      responses:
        204:
          description: "Room deleted successfully"
        404:
          description: "Room not found"
        500:
          description: "Internal Server Error"

  /bookings/{userID}/{dateTime}:
    get:
      tags:
        - bookings
      operationId: "ListBookingsByDateTime"
      summary: "Retrieve bookings for a user based on a datetime"
      parameters:
        - name: "userID"
          in: "path"
          description: "User ID for filtering bookings"
          required: true
          type: "integer"
        - name: "dateTime"
          in: "path"
          description: "Date and time for filtering bookings"
          required: true
          type: "string"
      responses:
        200:
          description: "List of bookings retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Booking"
        404:
          description: "Bookings not found"
        400:
          description: "Bad Request - Invalid input parameters"
        500:
          description: "Internal Server Error"


  /bookings/confirmed/{userID}:
    get:
      tags:
        - bookings
      operationId: "ListConfirmedBookings"
      summary: "Retrieve confirmed bookings for a user"
      parameters:
        - name: "userID"
          in: "path"
          description: "User ID for filtering confirmed bookings"
          required: true
          type: "integer"
      responses:
        200:
          description: "List of confirmed bookings retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Booking"
        404:
          description: "Bookings not found"
        400:
          description: "Bad Request - Invalid input parameters"
        500:
          description: "Internal Server Error"

definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"

  Hotel:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      location:
        type: "string"
      description:
        type: "string"
      rooms:
        type: "integer"

  Room:
    type: "object"
    properties:
      id:
        type: "integer"
      number:
        type: "string"
      hotel_id:
        type: "integer"

  CarRental:
    type: "object"
    properties:
      id:
        type: "integer"
      booked:
        type: "boolean"
  Booking:
    type: "object"
    properties:
      id:
        type: "integer"
      user_id:
        type: "integer"
      service_type:
        type: "string"
      service_id:
        type: "integer"
      from_date:
        type: "string"
        format: "date-time"
      to_date:
        type: "string"
        format: "date-time"
      confirmed:
        type: "boolean"
      penalty:
        type: "boolean"
      paid:
        type: "boolean"
